=== MrLiM/teraemu/TeraGame/data/schema/basestats.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/basestats"
    xmlns:xsd="http://angelis.com/basestats" xmlns:base="http://angelis.com/base" elementFormDefault="qualified">
    
    <!-- IMPORT -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base"/>
    
    <!-- TYPE -->
    <complexType name="BaseStatType">
        <attribute name="targetClass" type="base:ClassType"/>
        <attribute name="hp" type="integer"/>
        <attribute name="mp" type="integer"/>
        <attribute name="attack" type="integer"/>
        <attribute name="defense" type="integer"/>
        <attribute name="speed" type="integer"/>
        <attribute name="critChance" type="integer"/>
        <attribute name="critResist" type="integer"/>
    </complexType>
    
    <complexType name="BaseStatsType">
        <sequence>
            <element name="basestat" type="xsd:BaseStatType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!-- CONTENT -->
    <element name="basestats" type="xsd:BaseStatsType"/>
</schema>

=== MrLiM/teraemu/TeraGame/data/xml/basestats.xml
<?xml version="1.0" encoding="UTF-8"?>
<basestats xmlns="http://angelis.com/basestats" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://angelis.com/basestats ../schema/basestats.xsd "
>
    <basestat targetClass="WARRIOR" hp="903" mp="100" attack="66" defense="24" speed="120"
        critChance="50" critResist="80" />
    <basestat targetClass="LANCER" hp="689" mp="100" attack="49" defense="29" speed="105"
        critChance="50" critResist="80" />
    <basestat targetClass="SLAYER" hp="648" mp="100" attack="71" defense="21" speed="110"
        critChance="75" critResist="40" />
    <basestat targetClass="BERSERKER" hp="605" mp="100" attack="78" defense="26" speed="105"
        critChance="75" critResist="40" />
    <basestat targetClass="SORCERER" hp="582" mp="200" attack="64" defense="12" speed="110"
        critChance="25" critResist="30" />
    <basestat targetClass="ARCHER" hp="598" mp="50" attack="81" defense="27" speed="110"
        critChance="25" critResist="30" />
    <basestat targetClass="PRIEST" hp="527" mp="250" attack="32" defense="13" speed="110"
        critChance="20" critResist="25" />
    <basestat targetClass="MYSTIC" hp="580" mp="200" attack="32" defense="14" speed="110"
        critChance="20" critResist="25" />
</basestats>
