=== MrLiM/teraemu/TeraGame/data/schema/gathers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/gathers"
    xmlns:xsd="http://angelis.com/gathers" xmlns:base="http://angelis.com/base" elementFormDefault="qualified"
>
    <!-- IMPORTS -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base" />
    
    <!-- TYPES -->
    <complexType name="GatherType">
        <sequence>
            <element name="spawn" type="base:BaseSpawnType"  maxOccurs="unbounded"/>
        </sequence>
        <attribute name="id" type="integer" />
    </complexType>
    <complexType name="GathersType">
        <sequence>
            <element name="gather" type="xsd:GatherType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!-- CONTENT -->
    <element name="gathers" type="xsd:GathersType" />
</schema>

=== MrLiM/teraemu/TeraGame/data/xml/gathers.xml
<?xml version="1.0" encoding="UTF-8"?>
<gathers xmlns="http://angelis.com/gathers" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://angelis.com/gathers ../schema/gathers.xsd "
>
    <gather id="301">
        <spawn mapId="13" x="61031.203" y="-84792.54" z="-4006.272"/>
        <spawn mapId="13" x="61855.723" y="-82671.53" z="-4204.3096"/>
        <spawn mapId="13" x="59725.957" y="-84402.69" z="-4292.274"/>
        <spawn mapId="13" x="60011.203" y="-83202.36" z="-4311.3496"/>
        <spawn mapId="13" x="64530.004" y="-82145.71" z="-3771.6016"/>
        <spawn mapId="13" x="61000.535" y="-83858.57" z="-4287.6094"/>
        <spawn mapId="13" x="62298.66" y="-81956.836" z="-3880.8752"/>
        <spawn mapId="13" x="63608.234" y="-81688.88" z="-3792.7437"/>
        <spawn mapId="13" x="64400.598" y="-80637.02" z="-3447.8926"/>
        <spawn mapId="13" x="65254.64" y="-81166.734" z="-3466.921"/>
    </gather>
    <gather id="101">
        <spawn mapId="13" x="61599.02" y="-84192.6" z="-4155.872"/>
        <spawn mapId="13" x="64524.582" y="-80140.02" z="-3242.6094"/>
    </gather>
    <gather id="1">
        <spawn mapId="13" x="61367.887" y="-82062.51" z="-4179.9844"/>
        <spawn mapId="13" x="60320.062" y="-84214.734" z="-4311.1875"/>
        <spawn mapId="13" x="65991.63" y="-81071.32" z="-3319.6602"/>
        <spawn mapId="13" x="68667.05" y="-74404.63" z="-2950.9026"/>
        <spawn mapId="13" x="65156.195" y="-73963.84" z="-2938.9805"/>
        <spawn mapId="13" x="68698.99" y="-72426.14" z="-3228.044"/>
        <spawn mapId="13" x="69481.12" y="-73455.92" z="-3017.6558"/>
        <spawn mapId="13" x="69554.875" y="-72086.43" z="-3188.5117"/>
    </gather>
    <gather id="496">
        <spawn mapId="13" x="66039.07" y="-78435.305" z="-2991.3433"/>
        <spawn mapId="13" x="66182.91" y="-78422.74" z="-2990.3398"/>
        <spawn mapId="13" x="66018.25" y="-78306.51" z="-2992.4915"/>
        <spawn mapId="13" x="66097.0" y="-78361.21" z="-2989.8447"/>
        <spawn mapId="13" x="66165.24" y="-78289.75" z="-2986.7742"/>
    </gather>
    <gather id="409">
        <spawn mapId="13" x="65675.9" y="-72455.375" z="-3424.172"/>
    </gather>
</gathers>
