=== MrLiM/teraemu/TeraGame/data/schema/itemsets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/itemsets"
    xmlns:xsd="http://angelis.com/itemsets" xmlns:base="http://angelis.com/base" elementFormDefault="qualified">
    
    <!-- IMPORT -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base"/>
    
    <!-- TYPES -->
    <complexType name="ItemType">
        <attribute name="itemId" type="integer"/>
        <attribute name="slot" type="integer"/>
    </complexType>
    
    <complexType name="ItemSetType">
        <sequence>
            <element name="item" type="xsd:ItemType" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="targetClass" type="base:ClassType"/>
    </complexType>
    
    <complexType name="ItemSetsType">
        <sequence>
            <element name="itemset" type="xsd:ItemSetType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!-- CONTENT -->
    <element name="itemsets" type="xsd:ItemSetsType"/>
</schema>

=== MrLiM/teraemu/TeraGame/data/xml/itemsets.xml
<?xml version="1.0" encoding="UTF-8"?>
<itemsets xmlns="http://angelis.com/itemsets" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://angelis.com/itemsets ../schema/itemsets.xsd "
>
    <itemset targetClass="WARRIOR">
        <item itemId="10001" slot="1" />
        <item itemId="15004" slot="3" />
        <item itemId="15005" slot="4" />
        <item itemId="15006" slot="5" />
    </itemset>
    <itemset targetClass="LANCER">
        <item itemId="10002" slot="1" />
        <item itemId="15004" slot="3" />
        <item itemId="15005" slot="4" />
        <item itemId="15006" slot="5" />
    </itemset>
    <itemset targetClass="SLAYER">
        <item itemId="10003" slot="1" />
        <item itemId="15001" slot="3" />
        <item itemId="15002" slot="4" />
        <item itemId="15003" slot="5" />
    </itemset>
    <itemset targetClass="BERSERKER">
        <item itemId="10004" slot="1" />
        <item itemId="15001" slot="3" />
        <item itemId="15002" slot="4" />
        <item itemId="15003" slot="5" />
    </itemset>
    <itemset targetClass="SORCERER">
        <item itemId="10005" slot="1" />
        <item itemId="15007" slot="3" />
        <item itemId="15008" slot="4" />
        <item itemId="15009" slot="5" />
    </itemset>
    <itemset targetClass="ARCHER">
        <item itemId="10006" slot="1" />
        <item itemId="15004" slot="3" />
        <item itemId="15005" slot="4" />
        <item itemId="15006" slot="5" />
    </itemset>
    <itemset targetClass="PRIEST">
        <item itemId="10007" slot="1" />
        <item itemId="15007" slot="3" />
        <item itemId="15008" slot="4" />
        <item itemId="15009" slot="5" />
    </itemset>
    <itemset targetClass="MYSTIC">
        <item itemId="10008" slot="1" />
        <item itemId="15007" slot="3" />
        <item itemId="15008" slot="4" />
        <item itemId="15009" slot="5" />
    </itemset>
</itemsets>
